const crypto = require('node:crypto')
const fs = require('fs')
const path = require('path')
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins')

/**
 * Writes the app's network security config, and teaches the build to trust
 * one desktop's TLS certificate when there is one to trust.
 *
 * Android's default since targetSdk 28 is that cleartext is forbidden and only
 * the system's certificate authorities are trusted. Both halves of that are
 * wrong for this app, and in opposite directions, so this plugin always emits
 * a `network_security_config.xml` and always names it in the manifest — the
 * two branches below differ in what that file says, never in whether it
 * exists. It used to be written only when a certificate was lying around,
 * which meant a release build of a fresh clone had no config at all and could
 * not even reach a plain-HTTP daemon to pair with: the platform default cut
 * the connection with nothing in the log to act on.
 *
 * **Without `assets/desktop-ca.pem`.** The daemon speaks plain HTTP unless
 * somebody turned TLS on, so cleartext has to be permitted, and there is no
 * way to say *to whom*: the desktop is a DHCP lease, and a network security
 * config can name domains but not subnets. So this branch permits cleartext
 * app-wide and adds no trust anchor of its own. That is the honest cost of
 * shipping a build that has never been told which desktop it belongs to.
 *
 * **With `assets/desktop-ca.pem`.** Now the desktop's own names are known —
 * they are read straight back out of the certificate — so both permissions can
 * be narrowed to them. The base config, which covers every other host the app
 * ever talks to, forbids cleartext and trusts only the system anchors. A
 * single `domain-config` listing the names and addresses the certificate
 * covers is where the desktop's key becomes a trust anchor and where cleartext
 * stays allowed, so that a desktop with TLS off still pairs. Before this the
 * desktop's key sat in the base config, which made a self-signed key minted on
 * somebody's laptop an anchor for every TLS connection the app makes.
 *
 * Run `omarchy-connect tls trust` on the desktop to drop its certificate into
 * `assets/desktop-ca.pem`, then rebuild. Re-run it after the desktop's address
 * changes: the certificate is re-minted over the same key with new addresses
 * in it, and the names in this file are a copy taken at build time.
 */

const PEM = 'desktop-ca.pem'
const RAW_NAME = 'desktop_ca.pem'
const XML_NAME = 'network_security_config.xml'
const RESOURCE = '@xml/network_security_config'

const HEADER = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDesktopCa.js — do not edit by hand. -->`

/** Where `omarchy-connect tls trust` puts the certificate, if it ever ran. */
const certificateFor = (config) => path.join(config.modRequest?.projectRoot ?? process.cwd(), 'assets', PEM)

/**
 * Every host the certificate says it is good for, as a network security
 * config can spell them.
 *
 * Android matches a `<domain>` against the hostname the connection was opened
 * with, as a string, so an IPv4 literal out of the SANs works there exactly as
 * a name does — and an address is in fact what the phone dials, since that is
 * what the pairing QR carries. `127.0.0.1` is worth keeping for the same
 * reason it is in the certificate: it is the address an `adb reverse` tunnel
 * arrives on.
 */
function subjectNamesOf(pem) {
  const cert = new crypto.X509Certificate(pem)
  const names = (cert.subjectAltName || '')
    .split(',')
    .map((entry) => entry.trim().replace(/^(DNS|IP Address|IP):/, ''))
    .filter((entry) => entry && /^[A-Za-z0-9.\-_]+$/.test(entry))
  return [...new Set(names)].sort()
}

/**
 * The config file itself. `pem` is the certificate's text, or null when this
 * build has never been told which desktop it belongs to.
 */
function networkSecurityConfig(pem) {
  if (!pem) {
    return `${HEADER}
<network-security-config>
  <!-- No assets/desktop-ca.pem at build time: the desktop is unknown, so
       cleartext cannot be narrowed to it. Run \`omarchy-connect tls trust\`
       and rebuild to trade this for the narrow config. -->
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
</network-security-config>
`
  }
  const names = subjectNamesOf(pem)
  if (!names.length) {
    throw new Error(
      `assets/${PEM} names no hosts (no subjectAltName), so nothing can be scoped to it — ` +
        're-run `omarchy-connect tls trust` on the desktop to write a usable certificate.',
    )
  }
  const domains = names.map((name) => `    <domain includeSubdomains="false">${name}</domain>`).join('\n')
  return `${HEADER}
<network-security-config>
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
  <!-- The desktop this build was made for, and only it: its self-signed key
       is an anchor here and nowhere else, and cleartext is permitted here
       because the daemon speaks plain HTTP until TLS is switched on. -->
  <domain-config cleartextTrafficPermitted="true">
${domains}
    <trust-anchors>
      <certificates src="system" />
      <certificates src="@raw/desktop_ca" />
    </trust-anchors>
  </domain-config>
</network-security-config>
`
}

/**
 * Puts the config, and the certificate it may refer to, into `res/`. Returns
 * what it decided, which is the one line the prebuild prints about all this.
 */
function writeSecurityConfig(pem, resDir) {
  const raw = path.join(resDir, 'raw')
  const xml = path.join(resDir, 'xml')
  fs.mkdirSync(xml, { recursive: true })
  const contents = networkSecurityConfig(pem)
  fs.writeFileSync(path.join(xml, XML_NAME), contents)
  if (pem) {
    fs.mkdirSync(raw, { recursive: true })
    fs.writeFileSync(path.join(raw, RAW_NAME), pem)
  }
  return { scoped: Boolean(pem), names: pem ? subjectNamesOf(pem) : [] }
}

const withCertificateFiles = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const source = certificateFor(cfg)
      const pem = fs.existsSync(source) ? fs.readFileSync(source, 'utf8') : null
      const res = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res')
      const out = writeSecurityConfig(pem, res)
      console.log(
        out.scoped
          ? `withDesktopCa: trusting the desktop at ${out.names.join(', ')}, cleartext limited to it`
          : `withDesktopCa: no assets/${PEM}, so cleartext stays app-wide (run \`omarchy-connect tls trust\`)`,
      )
      return cfg
    },
  ])

const withManifestEntry = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults)
    application.$['android:networkSecurityConfig'] = RESOURCE
    return cfg
  })

module.exports = (config) => withManifestEntry(withCertificateFiles(config))
module.exports.networkSecurityConfig = networkSecurityConfig
module.exports.writeSecurityConfig = writeSecurityConfig
module.exports.subjectNamesOf = subjectNamesOf
