const fs = require('fs')
const path = require('path')
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins')

/**
 * Teaches an Android build to trust one desktop's TLS certificate.
 *
 * The daemon's certificate is self-signed and minted on the machine it belongs
 * to, so no certificate authority will ever vouch for it and Android will not
 * accept it out of the box. Android does, however, let an app name extra trust
 * anchors at build time — which fits exactly, because the person building this
 * app is the person who owns the desktop.
 *
 * Run `omarchy-connect tls trust` on the desktop to drop its certificate into
 * `assets/desktop-ca.pem`, then rebuild. Without that file this plugin does
 * nothing at all, so a plain build still works and simply stays on http.
 *
 * The system anchors are kept alongside ours: this adds a desktop to what the
 * phone trusts, it does not replace the internet's certificate authorities,
 * and it never enables cleartext.
 */

const PEM = 'desktop-ca.pem'
const RAW_NAME = 'desktop_ca.pem'
const XML_NAME = 'network_security_config.xml'
const RESOURCE = '@xml/network_security_config'

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDesktopCa.js — do not edit by hand. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
      <certificates src="@raw/desktop_ca" />
    </trust-anchors>
  </base-config>
</network-security-config>
`

const certificateFor = (config) => path.join(config.modRequest?.projectRoot ?? process.cwd(), 'assets', PEM)

const withCertificateFiles = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const source = certificateFor(cfg)
      if (!fs.existsSync(source)) return cfg

      const res = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res')
      const raw = path.join(res, 'raw')
      const xml = path.join(res, 'xml')
      fs.mkdirSync(raw, { recursive: true })
      fs.mkdirSync(xml, { recursive: true })
      fs.copyFileSync(source, path.join(raw, RAW_NAME))
      fs.writeFileSync(path.join(xml, XML_NAME), NETWORK_SECURITY_CONFIG)
      return cfg
    },
  ])

const withManifestEntry = (config) =>
  withAndroidManifest(config, (cfg) => {
    if (!fs.existsSync(path.join(cfg.modRequest.projectRoot, 'assets', PEM))) return cfg
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults)
    application.$['android:networkSecurityConfig'] = RESOURCE
    return cfg
  })

module.exports = (config) => withManifestEntry(withCertificateFiles(config))
